-- Graf 1: Identifikácia 10 lokalít s najvyššími priemernými zrážkami (analýza povodňových rizík)
SELECT l.POSTAL_CODE, AVG(f.PRECIPITATION) as AVG_RAIN 
FROM GLOBALWEATHER_DB.DWH.FACT_WEATHER_MEASUREMENTS f 
JOIN GLOBALWEATHER_DB.DWH.DIM_LOCATION l ON f.LOCATION_KEY = l.LOCATION_KEY 
GROUP BY l.POSTAL_CODE 
ORDER BY AVG_RAIN DESC 
LIMIT 10;

-- Graf 2: Maximálne namerané teploty podľa krajín (analýza teplotných rekordov a extrémov)
SELECT l.COUNTRY_NAME, MAX(f.TEMPERATURE) as PEAK_TEMPERATURE 
FROM GLOBALWEATHER_DB.DWH.FACT_WEATHER_MEASUREMENTS f 
JOIN GLOBALWEATHER_DB.DWH.DIM_LOCATION l ON f.LOCATION_KEY = l.LOCATION_KEY 
GROUP BY l.COUNTRY_NAME 
ORDER BY PEAK_TEMPERATURE DESC;

-- Graf 3: Sledovanie priemernej vlhkosti a oblačnosti podľa sezón (korelácia atmosférických javov)
SELECT d.SEASON, AVG(f.HUMIDITY) as AVG_HUMIDITY, AVG(f.CLOUD_COVER) as AVG_CLOUDS 
FROM GLOBALWEATHER_DB.DWH.FACT_WEATHER_MEASUREMENTS f 
JOIN GLOBALWEATHER_DB.DWH.DIM_DATE d ON f.DATE_KEY = d.DATE_KEY 
GROUP BY d.SEASON;

-- Graf 4: Analýza priemernej teploty a rýchlosti vetra podľa ročných období (sezónne trendy)
SELECT d.SEASON, AVG(f.TEMPERATURE) as AVG_TEMP, AVG(f.WIND_SPEED) as AVG_WIND 
FROM GLOBALWEATHER_DB.DWH.FACT_WEATHER_MEASUREMENTS f 
JOIN GLOBALWEATHER_DB.DWH.DIM_DATE d ON f.DATE_KEY = d.DATE_KEY 
GROUP BY d.SEASON 
ORDER BY CASE d.SEASON WHEN 'Spring' THEN 1 WHEN 'Summer' THEN 2 WHEN 'Autumn' THEN 3 WHEN 'Winter' THEN 4 END;

-- Graf 5: Trend teplotných anomálií porovnaním skutočnej teploty voči klimatickému normálu
SELECT d.DATE, AVG(f.TEMPERATURE) as SKUTOCNA_TEPLOTA, AVG(c.TEMPERATURE_NORM) as KLIMATICKY_NORMAL 
FROM GLOBALWEATHER_DB.DWH.FACT_WEATHER_MEASUREMENTS f 
JOIN GLOBALWEATHER_DB.DWH.DIM_DATE d ON f.DATE_KEY = d.DATE_KEY 
JOIN GLOBALWEATHER_DB.DWH.FACT_CLIMATOLOGY c ON f.LOCATION_KEY = c.LOCATION_KEY AND d.DAY_OF_YEAR = c.DAY_OF_YEAR 
GROUP BY d.DATE 
ORDER BY d.DATE;

-- Graf 6: Korelácia medzi atmosférickým tlakom a rýchlosťou vetra rozdelená podľa krajín
SELECT f.PRESSURE, f.WIND_SPEED, l.COUNTRY_NAME 
FROM GLOBALWEATHER_DB.DWH.FACT_WEATHER_MEASUREMENTS f 
JOIN GLOBALWEATHER_DB.DWH.DIM_LOCATION l ON f.LOCATION_KEY = l.LOCATION_KEY 
WHERE f.WIND_SPEED > 0 
LIMIT 100000;