USE WAREHOUSE SWAN_WH;
CREATE OR REPLACE DATABASE GlobalWeather_DB;
CREATE OR REPLACE SCHEMA GlobalWeather_DB.STAGING;
USE SCHEMA GlobalWeather_DB.STAGING;

CREATE OR REPLACE TABLE STG_HISTORY_DAY AS 
SELECT * FROM GLOBAL_WEATHER__CLIMATE_DATA_FOR_BI.STANDARD_TILE.HISTORY_DAY;

CREATE OR REPLACE TABLE STG_FORECAST_DAY AS 
SELECT * FROM GLOBAL_WEATHER__CLIMATE_DATA_FOR_BI.STANDARD_TILE.FORECAST_DAY;

CREATE OR REPLACE TABLE STG_CLIMATOLOGY_DAY AS 
SELECT * FROM GLOBAL_WEATHER__CLIMATE_DATA_FOR_BI.STANDARD_TILE.CLIMATOLOGY_DAY;

SELECT 'STG_HISTORY_DAY' AS table_name, COUNT(*) AS ROW_COUNT FROM STG_HISTORY_DAY
UNION ALL 
SELECT 'STG_FORECAST_DAY', COUNT(*) FROM STG_FORECAST_DAY
UNION ALL
SELECT 'STG_CLIMATOLOGY_DAY', COUNT(*) FROM STG_CLIMATOLOGY_DAY;

CREATE OR REPLACE TABLE CLEAN_WEATHER_DATA AS
SELECT
    'HISTORICAL' AS weather_type,
    DATE_VALID_STD AS DATE,
    POSTAL_CODE,
    COUNTRY,
    COALESCE(AVG_TEMPERATURE_AIR_2M_F, 0) AS TEMPERATURE,
    COALESCE(TOT_PRECIPITATION_IN, 0) AS PRECIPITATION,
    COALESCE(AVG_HUMIDITY_RELATIVE_2M_PCT, 0) AS HUMIDITY,
    COALESCE(AVG_WIND_SPEED_10M_MPH, 0) AS WIND_SPEED,
    COALESCE(AVG_CLOUD_COVER_TOT_PCT, 0) AS CLOUD_COVER,
    COALESCE(AVG_PRESSURE_2M_MB, 1013.25) AS PRESSURE
FROM STG_HISTORY_DAY
WHERE DATE_VALID_STD IS NOT NULL AND POSTAL_CODE IS NOT NULL AND COUNTRY IS NOT NULL
UNION ALL
SELECT
    'FORECAST' AS weather_type,
    DATE_VALID_STD AS DATE,
    POSTAL_CODE,
    COUNTRY,
    COALESCE(AVG_TEMPERATURE_AIR_2M_F, 0) AS TEMPERATURE,
    COALESCE(TOT_PRECIPITATION_IN, 0) AS PRECIPITATION,
    COALESCE(AVG_HUMIDITY_RELATIVE_2M_PCT, 0) AS HUMIDITY,
    COALESCE(AVG_WIND_SPEED_10M_MPH, 0) AS WIND_SPEED,
    COALESCE(AVG_CLOUD_COVER_TOT_PCT, 0) AS CLOUD_COVER,
    COALESCE(AVG_PRESSURE_2M_MB, 1013.25) AS PRESSURE    
FROM STG_FORECAST_DAY
WHERE DATE_VALID_STD IS NOT NULL AND POSTAL_CODE IS NOT NULL;

CREATE OR REPLACE TABLE CLEAN_CLIMATOLOGY_DATA AS
SELECT
    DOY_STD AS DAY_OF_YEAR,
    POSTAL_CODE,
    COUNTRY,
    COALESCE(AVG_OF__DAILY_AVG_TEMPERATURE_AIR_F, 0) AS TEMPERATURE_NORM,
    COALESCE(AVG_OF__POS_DAILY_TOT_PRECIPITATION_IN, 0) AS PRECIPITATION_NORM,
    COALESCE(AVG_OF__DAILY_AVG_HUMIDITY_RELATIVE_PCT, 0) AS HUMIDITY_NORM,
    COALESCE(AVG_OF__DAILY_AVG_WIND_SPEED_10M_MPH, 0) AS WIND_SPEED_NORM,
    COALESCE(AVG_OF__DAILY_AVG_CLOUD_COVER_TOT_PCT, 0) AS CLOUD_COVER_NORM,
    COALESCE(AVG_OF__DAILY_AVG_PRESSURE_SURFACE_MB, 1013.25) AS PRESSURE_NORM
FROM STG_CLIMATOLOGY_DAY
WHERE DOY_STD IS NOT NULL AND POSTAL_CODE IS NOT NULL AND COUNTRY IS NOT NULL;

CREATE OR REPLACE SCHEMA GlobalWeather_DB.DWH;
USE SCHEMA GlobalWeather_DB.DWH;

CREATE OR REPLACE TABLE DIM_DATE AS
SELECT DISTINCT 
    ROW_NUMBER() OVER (ORDER BY DATE) AS DATE_KEY,
    DATE,
    DAY(DATE) AS DAY,
    DAYOFWEEK(DATE) AS DAY_OF_WEEK,
    DAYNAME(DATE) AS DAY_OF_WEEK_NAME,
    MONTH(DATE) AS MONTH,
    MONTHNAME(DATE) AS MONTH_NAME,
    YEAR(DATE) AS YEAR,
    QUARTER(DATE) AS QUARTER,
    WEEKOFYEAR(DATE) AS WEEK_OF_YEAR,
    DAYOFYEAR(DATE) AS DAY_OF_YEAR,
    CASE 
        WHEN MONTH(DATE) IN (12, 1, 2) THEN 'Winter'
        WHEN MONTH(DATE) IN (3, 4, 5) THEN 'Spring'
        WHEN MONTH(DATE) IN (6, 7, 8) THEN 'Summer'
        ELSE 'Autumn'
    END AS SEASON,
    CASE WHEN DAYOFWEEK(DATE) IN (0, 6) THEN TRUE ELSE FALSE END AS IS_WEEKEND
FROM GLOBALWEATHER_DB.STAGING.CLEAN_WEATHER_DATA;

CREATE OR REPLACE TABLE GLOBALWEATHER_DB.DWH.DIM_LOCATION AS 
SELECT 
    ROW_NUMBER() OVER (ORDER BY COUNTRY, POSTAL_CODE) AS LOCATION_KEY,
    POSTAL_CODE,
    COUNTRY,
    COUNTRY_NAME,
    CONTINENT
FROM (
    SELECT DISTINCT 
        POSTAL_CODE, 
        COUNTRY,
        CASE 
            WHEN COUNTRY = 'US' THEN 'United States'
            WHEN COUNTRY IN ('CA', 'Canada') THEN 'Canada'
            WHEN COUNTRY IN ('MX', 'Mexico') THEN 'Mexico'
            ELSE COUNTRY
        END AS COUNTRY_NAME,
        CASE 
            WHEN COUNTRY IN ('US', 'CA', 'MX') THEN 'North America'
            WHEN COUNTRY IN ('BR', 'AR', 'CL', 'CO', 'PE') THEN 'South America'
            WHEN COUNTRY IN ('GB', 'FR', 'DE', 'UA', 'PL', 'IT', 'ES') THEN 'Europe'
            WHEN COUNTRY IN ('CN', 'JP', 'IN', 'KR', 'TH', 'VN') THEN 'Asia'
            WHEN COUNTRY IN ('AU', 'NZ') THEN 'Oceania'
            WHEN COUNTRY IN ('EG', 'ZA', 'NG', 'KE') THEN 'Africa'
            ELSE 'Other'
        END AS CONTINENT
    FROM GLOBALWEATHER_DB.STAGING.CLEAN_WEATHER_DATA
);

CREATE OR REPLACE TABLE DIM_WEATHER_TYPE AS 
SELECT 
    ROW_NUMBER() OVER (ORDER BY WEATHER_TYPE) AS WEATHER_TYPE_KEY,
    WEATHER_TYPE,
    CASE WEATHER_TYPE
        WHEN 'HISTORICAL' THEN 'Actual historical weather measurements'
        WHEN 'FORECAST' THEN 'Future weather predictions and forecasts'
    END AS DESCRIPTION
FROM (SELECT DISTINCT WEATHER_TYPE FROM GLOBALWEATHER_DB.STAGING.CLEAN_WEATHER_DATA);

CREATE OR REPLACE TABLE STG_WEATHER_METRICS AS
SELECT
    w.DATE,
    w.POSTAL_CODE,
    w.COUNTRY,
    w.WEATHER_TYPE,

    w.TEMPERATURE,
    w.PRECIPITATION,
    w.HUMIDITY,
    w.WIND_SPEED,
    w.CLOUD_COVER,
    w.PRESSURE,

    ROW_NUMBER() OVER (
        PARTITION BY w.POSTAL_CODE, w.COUNTRY, YEAR(w.DATE), MONTH(w.DATE)
        ORDER BY w.DATE
    ) AS DAY_NUMBER_IN_MONTH,

    LAG(w.TEMPERATURE) OVER (
        PARTITION BY w.POSTAL_CODE, w.COUNTRY
        ORDER BY w.DATE
    ) AS PREV_DAY_TEMPERATURE,
    
    w.TEMPERATURE
      - LAG(w.TEMPERATURE) OVER (
            PARTITION BY w.POSTAL_CODE, w.COUNTRY
            ORDER BY w.DATE
        ) AS TEMP_CHANGE_FROM_PREV_DAY,

    RANK() OVER (
        PARTITION BY w.POSTAL_CODE, w.COUNTRY, YEAR(w.DATE), MONTH(w.DATE)
        ORDER BY w.TEMPERATURE DESC
    ) AS TEMPERATURE_RANK_IN_MONTH,

    AVG(w.TEMPERATURE) OVER (
        PARTITION BY w.POSTAL_CODE, w.COUNTRY
        ORDER BY w.DATE
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ) AS TEMP_7DAY_MOVING_AVG,

    SUM(w.PRECIPITATION) OVER (
        PARTITION BY w.POSTAL_CODE, w.COUNTRY, YEAR(w.DATE), MONTH(w.DATE)
        ORDER BY w.DATE
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS CUMULATIVE_PRECIP_IN_MONTH

FROM GLOBALWEATHER_DB.STAGING.CLEAN_WEATHER_DATA w;

CREATE OR REPLACE TABLE FACT_WEATHER_MEASUREMENTS AS
SELECT
    ROW_NUMBER() OVER (ORDER BY d.DATE, l.LOCATION_KEY) AS MEASUREMENT_KEY,
    d.DATE_KEY,
    l.LOCATION_KEY,
    wt.WEATHER_TYPE_KEY,
    
    m.TEMPERATURE,
    m.PRECIPITATION,
    m.HUMIDITY,
    m.WIND_SPEED,
    m.CLOUD_COVER,
    m.PRESSURE,

    LAG(m.TEMPERATURE) OVER (PARTITION BY l.LOCATION_KEY, wt.WEATHER_TYPE_KEY ORDER BY d.DATE) AS PREV_DAY_TEMPERATURE,
    
    m.TEMPERATURE - LAG(m.TEMPERATURE) OVER (PARTITION BY l.LOCATION_KEY, wt.WEATHER_TYPE_KEY ORDER BY d.DATE) AS TEMP_CHANGE_FROM_PREV_DAY,

    AVG(m.TEMPERATURE) OVER (PARTITION BY l.LOCATION_KEY, wt.WEATHER_TYPE_KEY ORDER BY d.DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS TEMP_7DAY_MOVING_AVG,

    MAX(m.TEMPERATURE) OVER (PARTITION BY l.LOCATION_KEY, wt.WEATHER_TYPE_KEY, d.YEAR, d.MONTH) AS MAX_TEMP_IN_MONTH,
    
    MIN(m.TEMPERATURE) OVER (PARTITION BY l.LOCATION_KEY, wt.WEATHER_TYPE_KEY, d.YEAR, d.MONTH) AS MIN_TEMP_IN_MONTH

FROM GLOBALWEATHER_DB.STAGING.CLEAN_WEATHER_DATA m
JOIN GLOBALWEATHER_DB.DWH.DIM_DATE d ON m.DATE = d.DATE
JOIN GLOBALWEATHER_DB.DWH.DIM_LOCATION l ON m.POSTAL_CODE = l.POSTAL_CODE AND m.COUNTRY = l.COUNTRY
JOIN GLOBALWEATHER_DB.DWH.DIM_WEATHER_TYPE wt ON m.WEATHER_TYPE = wt.WEATHER_TYPE;


CREATE OR REPLACE TABLE FACT_CLIMATOLOGY AS 
SELECT 
    ROW_NUMBER() OVER (ORDER BY l.LOCATION_KEY, c.DAY_OF_YEAR) AS CLIMATOLOGY_KEY,
    l.LOCATION_KEY,
    c.DAY_OF_YEAR,
    c.TEMPERATURE_NORM,
    c.PRECIPITATION_NORM,
    c.HUMIDITY_NORM,
    c.WIND_SPEED_NORM,
    c.CLOUD_COVER_NORM,
    c.PRESSURE_NORM
FROM GLOBALWEATHER_DB.STAGING.CLEAN_CLIMATOLOGY_DATA c
JOIN DIM_LOCATION l ON c.POSTAL_CODE = l.POSTAL_CODE AND c.COUNTRY = l.COUNTRY;

SELECT 'DIM_DATE' as table_name, COUNT(*) FROM DIM_DATE
UNION ALL
SELECT 'DIM_LOCATION', COUNT(*) FROM DIM_LOCATION
UNION ALL
SELECT 'DIM_WEATHER_TYPE', COUNT(*) FROM DIM_WEATHER_TYPE
UNION ALL
SELECT 'FACT_WEATHER_MEASUREMENTS', COUNT(*) FROM FACT_WEATHER_MEASUREMENTS
UNION ALL
SELECT 'FACT_CLIMATOLOGY', COUNT(*) FROM FACT_CLIMATOLOGY;

ALTER WAREHOUSE SWAN_WH SET WAREHOUSE_SIZE = 'XSMALL';


SELECT * FROM FACT_CLIMATOLOGY LIMIT 20;
SELECT * FROM FACT_WEATHER_MEASUREMENTS LIMIT 20;

SELECT 
    DATE_KEY, 
    LOCATION_KEY, 
    TEMPERATURE, 
    PREV_DAY_TEMPERATURE, 
    TEMP_CHANGE_FROM_PREV_DAY
FROM GLOBALWEATHER_DB.DWH.FACT_WEATHER_MEASUREMENTS
WHERE LOCATION_KEY = (SELECT MIN(LOCATION_KEY) FROM DIM_LOCATION) 
ORDER BY DATE_KEY
LIMIT 10;